apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: avinashkanaparthy/mypython:4
        name: mypython
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "1"
